services:
  myserver:
    image: "flexvega/simple-worker:1.0.0-alpine"  # Imagen del contenedor
    container_name: "myserver"         # Nombre del contenedor
    network_mode: host                 # Usar la red del host
    restart: always                    # Pol√≠tica de reinicio para que siempre se reinicie el contenedor si falla
    ports:
      - "8080:8080"                   # Exponer puertos si es necesario
    deploy:
      resources:
        limits:
          cpus: '1.9'
          memory: 3.8G                # Limitar la RAM
    entrypoint: ["app-bluengo-worker", "server"]

